-- Limpar dados das tabelas (usando TRUNCATE CASCADE para lidar com foreign keys)
TRUNCATE TABLE public.designs RESTART IDENTITY CASCADE;
TRUNCATE TABLE public.cores RESTART IDENTITY CASCADE;
TRUNCATE TABLE public.tamanhos RESTART IDENTITY CASCADE;
TRUNCATE TABLE public.formas RESTART IDENTITY CASCADE;
TRUNCATE TABLE public.tipo_de_construcao RESTART IDENTITY CASCADE;
TRUNCATE TABLE public.tipo_de_sola RESTART IDENTITY CASCADE;
TRUNCATE TABLE public.tipo_de_pele RESTART IDENTITY CASCADE;